# Site
repository: "sproogen/modern-resume-theme"

# Personal info
name: "Fatima Saad"
title: "Your job title"
email: "your.email@example.com"
phone: "Your phone number"
website: "https://yourwebsite.com"

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: "your-github-username"
linkedin_username: "your-linkedin-username"

# About Section
about_profile_image: "images/profile.jpg"
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Fatima Saad, I am a student at Michigan State University pursuing a bachelor in Computer Science as well as a minor in Security in Management.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: "Office of Student Support and Accountability"
        sub_title: "Clerical Assistant"
        caption: "January 2024 - Present"
        description: |
          - Conducted confidential phone consultations addressing inquiries regarding student conduct, academic integrity, and intervention processes.
          - Employed effective time management and organizational skills to handle multiple tasks, ensuring smooth daily operations.
          - Maintained a welcoming environment for students and visitors, fostering positive interactions.

      - layout: right
        title: "Papaya Fruit Market"
        sub_title: "Head Cashier"
        caption: "July 2020 - August 2023"
        description: |
          - Provided exceptional customer service, resolving inquiries and ensuring a positive customer experience.
          - Managed financial transactions accurately and maintained proper records.
          - Excelled in a fast-paced environment, mastering multitasking and time management.

  - title: Community Involvement
    layout: list
    content:
      - layout: right
        title: "Women In Engineering"
        sub_title: "Mentor"
        caption: "August 2023 - Present"
        description: |
          - Mentored female engineering students, offering guidance in academic, professional, and personal development.
          - Conducted regular one-on-one mentoring sessions, providing advice and support.

      - layout: right
        title: "MSU Spartan Cyber Security"
        sub_title: "Team Member"
        caption: "January 2024 - April 2024"
        description: |
          - Competed in designing and implementing a supply chain security solution for medical devices.
          - Applied expertise in cryptography and security protocols.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: "Eli Lilly Project"
        link: "https://link-to-project.com"
        link_text: "Link Text"
        description: |
          - Collaborated with a team to optimize the filling and packaging process for Eli Lilly products.
          - Presented the project at an engineering fair, receiving positive feedback.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: "Michigan State University"
        sub_title: "Bachelor of Science, Computer Science"
        caption: "Minor in Security in Management"
        description: |
          - Description of your education and any relevant details.

  - title: Skills
    layout: text
    content: |
      - Programming: Python, C++
      - Familiar with Google Applications and Microsoft Office
      - Language Skills: Arabic (Native), English (Bilingual Proficiency)

# Footer
footer_show_references: true

# Build settings
remote_theme: "sproogen/modern-resume-theme"

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]

