# Content configuration version
version: 2

# Personal info
name: Fatima Saad
title: Computer Science Student
email: saadfat2@msu.edu
phone: (313) 398-9042
darkmode: true

# Social links
linkedin_username: fatima-saad-9276b726b
github_username:  # Leave blank if not using

# About Section
about_profile_image: images/headshot.jpeg
about_content: |
  I am Fatima Saad, a passionate and dedicated Computer Science student currently pursuing my Bachelor of Science degree at Michigan State University. With a strong foundation in programming languages such as Python and C++, I am eager to apply my skills in various projects and internships.

  Throughout my academic journey, I have developed a keen interest in security management, which is reflected in my minor. I am actively involved in community initiatives such as the Women In Engineering program, where I mentor fellow female engineering students, and the MSU Spartan Cyber Security team, where I contributed to designing a secure supply chain solution for medical devices.

  My professional experiences include working as a Clerical Assistant at the Office of Student Support and Accountability, where I honed my organizational and time management skills.
  My goal is to leverage my technical and interpersonal skills to make a meaningful impact in the field of computer science.

  Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/fatima-saad-9276b726b) or check out my projects on [GitHub](https://github.com/yourusername).

# Content sections


# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]

